"""init

Revision ID: 0bd63d22dce8
Revises: 
Create Date: 2025-12-07 17:12:16.546156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd63d22dce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('messages',
    sa.Column('messages_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('messages_id')
    )
    op.create_table('provider',
    sa.Column('provider_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_messages',
    sa.Column('chat_messages_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.messages_id'], ),
    sa.PrimaryKeyConstraint('chat_messages_id')
    )
    op.create_table('user_activity',
    sa.Column('user_activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_activity_id')
    )
    op.create_table('auth_identities',
    sa.Column('auth_identities_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_activity_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('provider_access_token', sa.Text(), nullable=True),
    sa.Column('provider_refresh_token', sa.Text(), nullable=True),
    sa.Column('provider_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.provider_id'], ),
    sa.ForeignKeyConstraint(['user_activity_id'], ['user_activity.user_activity_id'], ),
    sa.PrimaryKeyConstraint('auth_identities_id')
    )
    op.create_table('chat_participants',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['user_activity_id'], ['user_activity.user_activity_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_activity_id')
    )
    op.create_table('goals',
    sa.Column('goals_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_activity_id'], ['user_activity.user_activity_id'], ),
    sa.PrimaryKeyConstraint('goals_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goals_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user_authorization',
    sa.Column('user_authorization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_identities_id', sa.Integer(), nullable=False),
    sa.Column('user_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_identities_id'], ['auth_identities.auth_identities_id'], ),
    sa.ForeignKeyConstraint(['user_activity_id'], ['user_activity.user_activity_id'], ),
    sa.PrimaryKeyConstraint('user_authorization_id')
    )
    op.create_table('target_map',
    sa.Column('target_map_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('goals_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.goals_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('target_map_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_map')
    op.drop_table('user_authorization')
    op.drop_table('tasks')
    op.drop_table('goals')
    op.drop_table('chat_participants')
    op.drop_table('auth_identities')
    op.drop_table('user_activity')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('provider')
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
