"""nullable true

Revision ID: 39deeda9bf41
Revises: 9c2d71af4b10
Create Date: 2026-04-02 13:36:50.780813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39deeda9bf41'
down_revision: Union[str, Sequence[str], None] = '9c2d71af4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmaps', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('team_access_links_token_hash_key'), 'team_access_links', type_='unique')
    op.drop_index(op.f('ix_team_access_links_token_hash'), table_name='team_access_links')
    op.create_index(op.f('ix_team_access_links_token_hash'), 'team_access_links', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_access_links_token_hash'), table_name='team_access_links')
    op.create_index(op.f('ix_team_access_links_token_hash'), 'team_access_links', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('team_access_links_token_hash_key'), 'team_access_links', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('roadmaps', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
