"""nullable true

Revision ID: 40a583b78eef
Revises: 0dfb6c2a9f14
Create Date: 2026-05-09 19:37:13.517538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a583b78eef'
down_revision: Union[str, Sequence[str], None] = '0dfb6c2a9f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_access_roadmap_id'), table_name='roadmap_access')
    op.drop_index(op.f('ix_roadmap_access_user_id'), table_name='roadmap_access')
    op.drop_table('roadmap_access')
    op.alter_column('roadmap_copies', 'new_roadmap_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('roadmap_copies_new_roadmap_id_fkey'), 'roadmap_copies', type_='foreignkey')
    op.create_foreign_key(None, 'roadmap_copies', 'roadmaps', ['new_roadmap_id'], ['roadmap_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_copies', type_='foreignkey')
    op.create_foreign_key(op.f('roadmap_copies_new_roadmap_id_fkey'), 'roadmap_copies', 'roadmaps', ['new_roadmap_id'], ['roadmap_id'], ondelete='CASCADE')
    op.alter_column('roadmap_copies', 'new_roadmap_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('roadmap_access',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.roadmap_id'], name=op.f('roadmap_access_roadmap_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('roadmap_access_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_access_pkey'))
    )
    op.create_index(op.f('ix_roadmap_access_user_id'), 'roadmap_access', ['user_id'], unique=False)
    op.create_index(op.f('ix_roadmap_access_roadmap_id'), 'roadmap_access', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###
