"""initial

Revision ID: 6e596a84d481
Revises: e51d6ea8affc
Create Date: 2026-01-25 01:24:36.985611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e596a84d481'
down_revision: Union[str, Sequence[str], None] = 'e51d6ea8affc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_goals_id'), table_name='goals')
    op.drop_constraint(op.f('goals_user_id_fkey'), 'goals', type_='foreignkey')
    op.drop_column('goals', 'user_id')
    op.drop_column('goals', 'updated_at')
    op.drop_column('goals', 'created_at')
    op.drop_index(op.f('ix_roadmaps_roadmap_id'), table_name='roadmaps')
    op.drop_constraint(op.f('uq_goal_task'), 'roadmaps', type_='unique')
    op.drop_constraint(op.f('roadmaps_tasks_id_fkey'), 'roadmaps', type_='foreignkey')
    op.drop_constraint(op.f('roadmaps_user_id_fkey'), 'roadmaps', type_='foreignkey')
    op.drop_constraint(op.f('roadmaps_goals_id_fkey'), 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'tasks', ['tasks_id'], ['task_id'])
    op.create_foreign_key(None, 'roadmaps', 'goals', ['goals_id'], ['goals_id'])
    op.drop_column('roadmaps', 'user_id')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'estimated_duration_days')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('resources', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('estimated_duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.add_column('roadmaps', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key(op.f('roadmaps_goals_id_fkey'), 'roadmaps', 'goals', ['goals_id'], ['goals_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('roadmaps_user_id_fkey'), 'roadmaps', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('roadmaps_tasks_id_fkey'), 'roadmaps', 'tasks', ['tasks_id'], ['task_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_goal_task'), 'roadmaps', ['goals_id', 'tasks_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_roadmaps_roadmap_id'), 'roadmaps', ['roadmap_id'], unique=False)
    op.add_column('goals', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('goals_user_id_fkey'), 'goals', 'users', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_goals_goals_id'), 'goals', ['goals_id'], unique=False)
    # ### end Alembic commands ###
