"""initial tables 3

Revision ID: 907c59b2e305
Revises: 
Create Date: 2025-12-15 04:15:44.499780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '907c59b2e305'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('chat_messages_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.messages_id'], ),
    sa.PrimaryKeyConstraint('chat_messages_id')
    )
    op.create_table('user_activity',
    sa.Column('user_activity_id', sa.Integer(), nullable=False),
    sa.Column('auth_identities_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_messages_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_identities_id'], ['auth_identities.auth_identities_id'], ),
    sa.ForeignKeyConstraint(['chat_messages_id'], ['chat_messages.chat_messages_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_activity_id')
    )
    op.drop_table('providers')
    op.drop_table('target_maps')
    op.drop_table('user_activities')
    op.add_column('auth_identities', sa.Column('auth_identities_id', sa.Integer(), nullable=False))
    op.add_column('auth_identities', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('auth_identities_user_activity_id_fkey'), 'auth_identities', type_='foreignkey')
    op.drop_constraint(op.f('auth_identities_provider_id_fkey'), 'auth_identities', type_='foreignkey')
    op.drop_column('auth_identities', 'auth_identity_id')
    op.drop_column('auth_identities', 'user_activity_id')
    op.drop_column('auth_identities', 'provider_id')
    op.drop_column('auth_identities', 'password_hash')
    op.add_column('chats', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('chats', 'is_group')
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'title')
    op.add_column('goals', sa.Column('goals_id', sa.Integer(), nullable=False))
    op.add_column('goals', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('goals_user_activity_id_fkey'), 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'user_activity', ['user_activity_id'], ['user_activity_id'])
    op.drop_column('goals', 'goal_id')
    op.drop_column('goals', 'target_date')
    op.drop_column('goals', 'completed_at')
    op.add_column('messages', sa.Column('messages_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('messages_sender_user_activity_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'message_id')
    op.drop_column('messages', 'sender_user_activity_id')
    op.drop_column('messages', 'chat_id')
    op.add_column('tasks', sa.Column('goals_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tasks_target_map_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'goals', ['goals_id'], ['goals_id'])
    op.drop_column('tasks', 'target_map_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.add_column('tasks', sa.Column('target_map_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_target_map_id_fkey'), 'tasks', 'target_maps', ['target_map_id'], ['target_map_id'])
    op.drop_column('tasks', 'goals_id')
    op.add_column('messages', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sender_user_activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('messages', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['chat_id'])
    op.create_foreign_key(op.f('messages_sender_user_activity_id_fkey'), 'messages', 'user_activities', ['sender_user_activity_id'], ['user_activity_id'])
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'messages_id')
    op.add_column('goals', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key(op.f('goals_user_activity_id_fkey'), 'goals', 'user_activities', ['user_activity_id'], ['user_activity_id'])
    op.drop_column('goals', 'created_at')
    op.drop_column('goals', 'goals_id')
    op.add_column('chats', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('is_group', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('chats', 'created_at')
    op.drop_column('chats', 'name')
    op.add_column('auth_identities', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('auth_identities', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('auth_identities', sa.Column('user_activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('auth_identities', sa.Column('auth_identity_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_foreign_key(op.f('auth_identities_provider_id_fkey'), 'auth_identities', 'providers', ['provider_id'], ['provider_id'])
    op.create_foreign_key(op.f('auth_identities_user_activity_id_fkey'), 'auth_identities', 'user_activities', ['user_activity_id'], ['user_activity_id'])
    op.drop_column('auth_identities', 'password')
    op.drop_column('auth_identities', 'auth_identities_id')
    op.create_table('user_activities',
    sa.Column('user_activity_id', sa.INTEGER(), server_default=sa.text("nextval('user_activities_user_activity_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_activities_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_activity_id', name='user_activities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('target_maps',
    sa.Column('target_map_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_activity_id'], ['user_activities.user_activity_id'], name=op.f('target_maps_user_activity_id_fkey')),
    sa.PrimaryKeyConstraint('target_map_id', name=op.f('target_maps_pkey'))
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('auth_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('providers_pkey')),
    sa.UniqueConstraint('name', name=op.f('providers_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('user_activity')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
